"""check ingredient changes

Revision ID: 134546b5f5b2
Revises: b2c4e7f1a9d0
Create Date: 2026-06-06 19:25:00.369548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134546b5f5b2'
down_revision = 'b2c4e7f1a9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expert_concern', sa.String(length=3), nullable=True))
        batch_op.drop_column('revant_concern')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('nutriscore_grade',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('nutriscore_grade',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revant_concern', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
        batch_op.drop_column('expert_concern')

    # ### end Alembic commands ###
