"""final migration

Revision ID: a260cafcc1af
Revises: 134546b5f5b2
Create Date: 2026-06-08 17:50:57.298960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a260cafcc1af'
down_revision = '134546b5f5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('barcodes', sa.Text(), nullable=False),
    sa.Column('verdict_text', sa.Text(), nullable=True),
    sa.Column('winner_barcode', sa.String(length=20), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('ingredients',
    sa.Column('ins_no', sa.String(length=20), nullable=False),
    sa.Column('e_number', sa.String(length=20), nullable=True),
    sa.Column('name_english', sa.String(length=255), nullable=False),
    sa.Column('name_hindi', sa.String(length=255), nullable=True),
    sa.Column('functional_class', sa.String(length=100), nullable=True),
    sa.Column('harm_level', sa.Integer(), nullable=False),
    sa.Column('harm_severity', sa.String(length=20), nullable=True),
    sa.Column('color_code', sa.String(length=10), nullable=True),
    sa.Column('harm_reason', sa.Text(), nullable=True),
    sa.Column('expert_concern', sa.String(length=3), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('fssai_permitted', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ins_no')
    )
    op.create_table('products',
    sa.Column('barcode', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('ingredients_text', sa.Text(), nullable=True),
    sa.Column('ingredients_hash', sa.String(length=64), nullable=True),
    sa.Column('additives_tags', sa.Text(), nullable=True),
    sa.Column('nova_group', sa.Integer(), nullable=True),
    sa.Column('nutriscore_grade', sa.String(length=20), nullable=True),
    sa.Column('energy_kcal_100g', sa.Float(), nullable=True),
    sa.Column('protein_100g', sa.Float(), nullable=True),
    sa.Column('fat_100g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_100g', sa.Float(), nullable=True),
    sa.Column('trans_fat_100g', sa.Float(), nullable=True),
    sa.Column('sugars_100g', sa.Float(), nullable=True),
    sa.Column('sodium_100g', sa.Float(), nullable=True),
    sa.Column('fiber_100g', sa.Float(), nullable=True),
    sa.Column('serving_size_g', sa.Float(), nullable=True),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('packaging', sa.String(length=200), nullable=True),
    sa.Column('manufacturing_places', sa.String(length=200), nullable=True),
    sa.Column('origins', sa.String(length=200), nullable=True),
    sa.Column('labels_tags', sa.String(length=500), nullable=True),
    sa.Column('food_pharmer_score', sa.Integer(), nullable=True),
    sa.Column('score_band', sa.String(length=10), nullable=True),
    sa.Column('verdict_text', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('data_verified', sa.Boolean(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_table('unknown_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_as_found', sa.String(length=255), nullable=False),
    sa.Column('product_barcode', sa.String(length=20), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_as_found')
    )
    op.create_table('url_cache',
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('product_data', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('product_barcode', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_subject', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('ingredient_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=False),
    sa.Column('old_hash', sa.String(length=64), nullable=True),
    sa.Column('new_hash', sa.String(length=64), nullable=True),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barcode'], ['products.barcode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_changes_barcode'), ['barcode'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('input_method', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('base_score', sa.Integer(), nullable=True),
    sa.Column('personalised_score', sa.Integer(), nullable=True),
    sa.Column('verdict_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barcode'], ['products.barcode'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmi_category_indian', sa.String(length=20), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('diet_type', sa.String(length=30), nullable=True),
    sa.Column('activity_level', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))

    op.drop_table('scans')
    with op.batch_alter_table('ingredient_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_changes_barcode'))

    op.drop_table('ingredient_changes')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('url_cache')
    op.drop_table('unknown_ingredients')
    op.drop_table('products')
    op.drop_table('ingredients')
    op.drop_table('comparison_cache')
    # ### end Alembic commands ###
